services:
  - type: web
    name: paros-bg-remover
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: U2NET_HOME
        value: /tmp/u2net
